server:
  port: ${PORT:8080}

spring:
  application:
    name: ${APPLICATION_NAME:hcm202}

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:hcm202}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: gemma3:12b
          temperature: 0.7

    retry:
      max-attempts: 1


#  # Nếu bạn dùng PGVector sau này, hãy bỏ comment và chỉnh thụt lề như sau:
#  vectorstore:
#    pgvector:
#      index-type: HNSW
#      dimensions: 1536
#      initialize-schema: true
#      table-name: hcm202_vector
#      distance-type: cosine_distance