server:
  port: ${PORT:8080}

spring:
  application:
    name: ${APPLICATION_NAME:hcm202}

  datasource:
#    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:hcm202}?options=-c%20timezone=UTC
#    username: ${DB_USER:postgres}
#    password: ${DB_PASSWORD:123456}
#    driver-class-name: org.postgresql.Driver

    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d5igfbp5pdvs73c173ig-a.singapore-postgres.render.com/hcm202}
    username: ${SPRING_DATASOURCE_USERNAME:hcm202_user}
    password: ${SPRING_DATASOURCE_PASSWORD:qYj08hG0XMSiBfn8q4givoPfGaSpJyAB}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  ai:
    ollama:
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
      chat:
        options:
          model: ${OLLAMA_MODEL:gemma2:2b}
          temperature: 0.4

    retry:
      max-attempts: 1

    vectorstore:
      pgvector:
        index-type: HNSW
        dimensions: 1024
        initialize-schema: true
        table-name: hcm202_vector

